import React, { useEffect, useRef } from 'react';
import { X } from 'lucide-react';

interface RegulaminModalFooterProps {
  isOpen: boolean;
  onClose: () => void;
}

export const RegulaminModalFooter: React.FC<RegulaminModalFooterProps> = ({ isOpen, onClose }) => {
  const modalRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (modalRef.current && !modalRef.current.contains(event.target as Node)) {
        onClose();
      }
    };

    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50">
      <div 
        ref={modalRef}
        className="bg-white rounded-2xl max-w-2xl w-full max-h-[80vh] overflow-y-auto p-6 shadow-lg"
      >
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-xl font-semibold">Regulamin</h2>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-full transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>
        <div className="prose prose-sm max-w-none">
          <p style={{ textAlign: 'justify', fontSize: '12px' }}>
          <p>Przed rozpoczęciem korzystania z serwisu internetowego www.raport-erp.pl Usługobiorcy są zobowiązani zapoznać się z treścią Regulaminu.</p>
<p><strong>REGULAMIN SERWISU INTERNETOWEGO WWW.RAPORT-ERP.PL</strong></p>
<p><strong>I. Postanowienia ogólne</strong><br /><strong>II. Definicje</strong><br /><strong>III. Rodzaj i zakres usług elektronicznych</strong><br /><strong>IV. Warunki świadczenia i zawierania umów o świadczenie usług elektronicznych</strong><br /><strong>V. Tryb postępowania reklamacyjnego</strong><br /><strong>VI. Własność intelektualna</strong><br /><strong>VII. Odpowiedzialność </strong><br /><strong>VIII. Postanowienia końcowe</strong></p>
<p>&nbsp;</p>
<p><strong>I. POSTANOWIENIA OGÓLNE</strong><br />1. Serwis internetowy działający pod adresem www.raport-erp.pl prowadzony jest przez Patrycjusza Jaworskiego wykonującego działalność gospodarczą pod firmą ERP-VIEW.PL PATRYCJUSZ JAWORSKI wpisaną do Centralnej Ewidencji i Informacji o Działalności Gospodarczej Rzeczypospolitej Polskiej prowadzonej przez ministra właściwego do spraw gospodarki, adres miejsca wykonywania działalności oraz adres do doręczeń: ul. Dzielna 25/17, 54-152 Wrocław, NIP: 8942457040, REGON: 020881427, adres poczty elektronicznej (e-mail): p.jaworski@erp-view.pl, tel. +48 502 578 119.<br />2. Serwis www.raport-erp.pl działa na zasadach określonych w niniejszym Regulaminie i jest przeznaczony dla Przedsiębiorców. <br />3. Regulamin określa rodzaje i zakres usług świadczonych drogą elektroniczną przez Serwis www.raport-erp.pl, zasady świadczenia tych usług, warunki zawierania i rozwiązywania umów o świadczenie usług drogą elektroniczną, a także tryb postępowania reklamacyjnego.<br />4. Każdy Usługobiorca z chwilą podjęcia czynności zmierzających do korzystania z Usług Elektronicznych Serwisu www.raport-erp.pl, zobowiązany jest do przestrzegania postanowień niniejszego Regulaminu.<br />5. Serwis oraz Usługodawca nie prowadzi sprzedaży produktów oraz usług prezentowanych w Serwisie.<br />6. Wszystkie nazwy handlowe, nazwy produktów, firm i ich logo użyte na stronie internetowej Serwisu pod adresem www.raport-erp.pl należą do ich właścicieli i są używane wyłącznie w celach identyfikacyjnych. Mogą być one zastrzeżonymi znakami towarowymi. Wszystkie materiały, opisy i zdjęcia prezentowane na stronie internetowej Serwisu pod adresem www.raport-erp.pl użyte są w celach informacyjnych.<br />7. W sprawach nieuregulowanych w niniejszym Regulaminie mają zastosowanie przepisy: <br />a) Kodeksu cywilnego;<br />b) Ustawy o prawach konsumenta z dnia 30 maja 2014 r. (Dz. U. 2014 poz. 827);<br />c) Ustawy o prawie autorskim i prawach pokrewnych z dnia 4 lutego 1994 r. (Dz. U. nr 24, poz. 83 z późniejszymi zmianami);<br />d) Ustawy o świadczeniu usług drogą elektroniczną z dnia 18 lipca 2002 r. (Dz. U. Nr 144, poz. 1204 ze zm.) oraz inne właściwe przepisy prawa polskiego.</p>
<p><strong>II. DEFINICJE</strong><br />1. KONSUMENT - osoba fizyczna, która dokonuje z przedsiębiorcą czynności prawnej niezwiązanej bezpośrednio z jej działalnością gospodarczą lub zawodową.<br />2. LICENCJA - umowa licencyjna w rozumieniu rozdziału 5 ustawy o prawie autorskim i prawach pokrewnych z dnia 4 lutego 1994r. (Dz. U. Nr 24, poz. 83).<br />3. PRZEDSIĘBIORCA - osoba fizyczna, osoba prawna i jednostka organizacyjna, o której mowa w art. 331 § 1 kodeksu cywilnego, prowadząca we własnym imieniu działalność gospodarczą lub zawodową.<br />4. RAPORT ERP - szczegółowa bezpłatna analiza dostępnych na polskim rynku systemów ERP, wykonana w oparciu o funkcjonalności istotne z punktu widzenia przedsiębiorcy prowadzącego działalność w Polsce. Warunkiem otrzymania bezpłatnego raportu jest wyrażenie zgody na przekazanie danych kontaktowych partnerom raportu w celu przedstawienia oferty handlowej.<br />5. PARTNERZY RAPORTU:<br /> - Microsoft Sp. z o.o. Aleje Jerozolimskie 195A 02-222 Warszawa NIP: 5270103391<br /> - Macrologic S.A. ul. Kłopotowskiego 22 03-717 Warszawa NIP: 5220002825<br /> - Oracle Polska Sp. z o.o. ul. Przyokopowa 31 01-208 Warszawa NIP: 5270201490<br /> - Simple S.A. ul. Bronisława Czecha 49/51 04-555 Warszawa NIP: 1130022578<br /> - BIURO PROJEKTOWANIA SYSTEMÓW CYFROWYCH Sp. z o.o. Al. Walentego Roździeńskiego 188H 40-203 Katowice NIP: 6340134346- IT.Integro Sp. z o.o. ul. Ząbkowicka 12 60-166 Poznań NIP:&nbsp; <br />&nbsp;&nbsp; 7780021279<br /> - Soneta Sp. z o.o. u. J. Kustronia 44A 30-432 Kraków NIP: 6792705304<br /> - Sygnity Business Solutions S.A. ul. Dąbrowskiego 12 65-021 Zielona Góra NIP: 9290094326<br /> - Unit4 Polska Sp. z o.o. ul. Powstańców Śląskich 7A 53-332 Wrocław NIP: 8992737741<br /> - abas Business Solutions Poland Sp. z o.o. Al. Walentego Roździeńskiego 188C NIP: 6342865769<br /> - ANEGIS Sp. z o.o. ul. Św. Mikołaja 7 50-125 Wrocław NIP: 8971791899<br />6. REGULAMIN - niniejszy regulamin Serwisu.<br />7. SERWIS - serwis internetowy Usługodawcy działający pod adresem www.raport-erp.pl.<br />8. USŁUGODAWCA – Patrycjusz Jaworski wykonujący działalność gospodarczą pod firmą ERP-VIEW.PL PATRYCJUSZ JAWORSKI, ul. Dzielna 25/17, 54-152 Wrocław, NIP: 8942457040, REGON: 020881427.<br />9. USŁUGOBIORCA, UŻYTKOWNIK –osoba fizyczna, osoba prawna albo jednostka organizacyjna nieposiadająca osobowości prawnej, której ustawa przyznaje zdolność prawną, korzystająca z Usługi Elektronicznej.<br />10. USŁUGA ELEKTRONICZNA – usługa świadczona drogą elektroniczną przez Usługodawcę na rzecz Usługobiorcy za pośrednictwem Serwisu.<br />11. ZLECENIE - informacja umieszczana przez Zlecającego w Formularzu Raportu ERP, będąca wyrazem woli otrzymania szczegółowej analizy w postaci Raportu ERP.<br />12. ZLECAJĄCY - Użytkownik składający za pośrednictwem Serwisu zamówienie wykonania Raportu ERP przez Usługodawcę.</p>
<p>&nbsp;</p>
<p><strong>III. RODZAJ I ZAKRES USŁUG ELEKTRONICZNYCH</strong><br />1. Usługodawca umożliwia za pośrednictwem Serwisu korzystanie z Usługi Elektronicznej polegającej na korzystaniu z formularza Raportu ERP.<br />2. Świadczenie Usługi na rzecz Usługobiorców w Serwisie odbywa się na warunkach określonych w Regulaminie.<br />3. Usługodawca ma prawo do zamieszczania na stronie Serwisu treści reklamowych. Treści te stanowią integralną część Serwisu i prezentowanych w nim materiałów.</p>
<p>IV. WARUNKI ŚWIADCZENIIA I ZAWIERANIA UMÓW O ŚWIADCZENIE USŁUG ELEKTRONICZNYCH <br />1. Świadczenie Usług Elektronicznych określonych w rozdziale III pkt 1 Regulaminu przez Usługodawcę jest nieodpłatne.<br />2. Umowa o świadczenie Usługi Elektronicznej polegającej na korzystaniu z formularza Raportu ERP, zawierana jest na czas oznaczony i ulega rozwiązaniu z chwilą zaprzestania korzystania z tej Usługi przez Użytkownika.<br />3. Wymagania techniczne niezbędne do współpracy z systemem teleinformatycznym, którym posługuje się Usługodawca: <br />a) komputer (lub urządzenie mobilne) z dostępem do Internetu,<br />b) dostęp do poczty elektronicznej,<br />c) przeglądarka internetowa,<br />d) włączenie w przeglądarce internetowej Cookies oraz Javascript.<br />4. Usługobiorca zobowiązany jest do korzystania z Serwisu w sposób zgodny z prawem i dobrymi obyczajami mając na uwadze poszanowanie dóbr osobistych i praw własności intelektualnej osób trzecich.<br />5. Usługobiorca zobowiązany jest do wprowadzania danych zgodnych ze stanem faktycznym.<br />6. Usługobiorcę obowiązuje zakaz dostarczania treści o charakterze bezprawnym.<br />7. Usługobiorca zobowiązany jest do powstrzymywania się od jakichkolwiek działań, które mogłyby utrudniać lub zakłócać funkcjonowanie Serwisu oraz działań na szkodę Usługodawcy oraz innych podmiotów.</p>
<p><strong>V. TRYB POSTĘPOWANIA REKLAMACYJNEGO</strong><br />1. Reklamacje związane ze świadczeniem Usług Elektronicznych przez Usługodawcę:<br />a) Reklamacje związane ze świadczeniem Usług Elektronicznych za pośrednictwem Serwisu Usługobiorca może składać za pośrednictwem poczty elektronicznej na adres: p.jaworski@erp-view.pl.<br />b) W powyższej wiadomości e-mail, należy podać jak najwięcej informacji i okoliczności dotyczących przedmiotu reklamacji, w szczególności rodzaj i datę wystąpienia nieprawidłowości oraz dane biurowe. Podane informacje znacznie ułatwią i przyspieszą rozpatrzenie reklamacji przez Usługodawcę.<br />c) Rozpatrzenie reklamacji przez Usługodawcę następuje niezwłocznie, nie później niż w terminie 14 dni od momentu zgłoszenia.<br />d) Odpowiedź Usługodawcy w sprawie reklamacji jest wysyłana na adres e-mail Usługobiorcy podany w zgłoszeniu reklamacyjnym lub w inny podany przez Usługobiorcę sposób.</p>
<p><strong>VI. WŁASNOŚĆ INTELEKTUALNA</strong><br />1. Wszystkie treści zamieszczone na stronie internetowej pod adresem www.raport-erp.pl, w tym nazwa Serwisu, jego funkcjonalności, wygląd graficzny, logotypy, elementy grafiki, układ i kompozycja tych elementów (tzw. "layout"), znaki towarowe, oprogramowanie oraz baza danych korzystają z ochrony prawnoautorskiej i (z wyjątkiem treści zamieszczanych przez Usługobiorców oraz elementów wykorzystywanych na zasadach licencji, przeniesienia praw autorskich lub dozwolonego użytku) są własnością Patrycjusza Jaworskiego wykonującego działalność gospodarczą w ERP-VIEW.PL PATRYCJUSZ JAWORSKI, Dzielna 25/17, 54-152 Wrocław, NIP: 8942457040, REGON: 020881427. Usługobiorca ponosi pełną odpowiedzialność za szkodę wyrządzoną Usługodawcy, będącą następstwem użycia jakiejkolwiek zawartości strony www.raport-erp.pl, bez zgody Usługodawcy.<br />2. Jakiekolwiek wykorzystanie przez kogokolwiek, bez wyraźnej pisemnej zgody Usługodawcy, któregokolwiek z elementów składających się na treść oraz zawartość strony www.raport-erp.pl stanowi naruszenie prawa autorskiego przysługującego Usługodawcy i skutkuje odpowiedzialnością cywilnoprawną oraz karną.<br />3. Usługobiorca przesyłając Serwisowi pliki oraz inne treści cyfrowe potwierdza swoje prawo do dysponowania nimi oraz ponosi wyłączną odpowiedzialność za naruszenia autorskich praw majątkowych i pokrewnych, danych osobowych oraz dóbr osobistych osób trzecich, a w przypadku wystąpienia przez jakąkolwiek osobę z jakimikolwiek roszczeniami lub żądaniami w stosunku do Serwisu z tego tytułu, zobowiązuję się zwolnić Serwis i Usługodawcę z wszelkiej odpowiedzialności w związku z naruszeniami oraz do całkowitego zaspokojenia roszczeń osób trzecich w tym zakresie.</p>
<p><strong>VII. ODPOWIEDZIALNOŚĆ</strong> <br />1. Usługodawca podejmuje wszelkie dostępne mu środki, w celu ochrony danych Użytkowników.<br />2. Usługodawca dołoży wszelkich starań, aby dane dostępne w Serwisie były kompletne i aktualne oraz prezentowane z należytą starannością, z uwzględnieniem istniejących okoliczności faktycznych i prawnych, w granicach dopuszczalnych przez prawo i przy pełnym poszanowaniu praw konsumenta.<br />3. Użytkownicy ponoszą pełną odpowiedzialność za złamanie prawa bądź szkodę wywołaną ich działaniami w Serwisie, w szczególności podaniem nieprawdziwych danych, ujawnieniem informacji niejawnej lub innych tajemnic ustawowo chronionych, naruszeniem dóbr osobistych lub praw autorskich oraz praw pokrewnych, a także przetwarzaniem danych osobowych Użytkowników niezgodnie z celami Serwisu lub z naruszeniem przepisów ustawy o ochronie danych osobowych.<br />4. Usługodawca zobowiązuje się w miarę możliwości informować z wyprzedzeniem Użytkowników o możliwych zakłóceniach w funkcjonowaniu Serwisu, w szczególności o przerwach w dostępie.<br />5. Usługodawca nie jest odpowiedzialny w stosunku do Usługobiorców niebędących Konsumentami:<br />a) za jakiekolwiek szkody i straty bezpośrednio lub pośrednio (łącznie ze szkodami z tytułu utraty zysków z prowadzenia przedsiębiorstwa, przerw w działalności przedsiębiorstwa lub utraty informacji gospodarczej oraz innymi szkodami o charakterze majątkowym), powstałe z powodu użycia, niemożliwości użycia lub błędnego działania oprogramowania Serwisu, szkody powstałe w wyniku wyłączenia lub awarii systemu teleinformatycznego, awarii sieci energetycznej,<br />b) w związku z niewłaściwym korzystaniem z Serwisu przez Usługobiorcę niebędącego Konsumentem oraz nieprawidłowym funkcjonowaniem sprzętu komputerowego, oprogramowania komputerowego czy też systemu łączności, za pomocą których Usługobiorca łączy się z systemem Serwisu,<br />c) za ewentualne szkody powstałe w wyniku błędów, awarii i przerw w funkcjonowaniu Serwisu lub spowodowane nieprawidłowym zapisem lub odczytem danych pobieranych przez Usługobiorców,<br />d) za zakłócenia w prawidłowym funkcjonowaniu Serwisu, a także utratę danych Usługobiorców niebędących Konsumentami powstałe w wyniku działania siły wyższej lub osób trzecich,<br />e) za działania osób trzecich polegające na niezgodnym z powszechnie obowiązującym prawem lub Regulaminem wykorzystywaniu danych oraz materiałów umieszczonych w Serwisie,<br />f) za niemożność zalogowania się w systemie Serwisu spowodowaną w szczególności: jakością połączenia, awarią systemu teleinformatycznego lub sieci energetycznej, błędną konfiguracją oprogramowania Usługobiorców niebędących Konsumentami,<br />g) za skutki związane z utratą hasła.</p>
<p><strong>VIII. POSTANOWIENIA KOŃCOWE</strong><br />1. Umowy zawierane poprzez Serwis zawierane są zgodnie z prawem polskim.<br />2. Zmiany dokonane w Regulaminie Serwisu przez Usługodawcę, wiążą Usługobiorcę, pod warunkiem iż został on prawidłowo poinformowany o zmianach i nie wypowiedział umowy o świadczenie usług drogą elektroniczną w terminie 14 dni od dnia powiadomienia Usługobiorcy o zmianach przez Serwis. <br />3. Wszelkie spory wynikłe między Usługodawcą, a Usługobiorcami będą rozstrzygane w pierwszej kolejności na drodze negocjacji, z intencją polubownego zakończenia sporu. Jeśli jednak nie byłoby to możliwe, lub też byłoby niesatysfakcjonujące dla którejkolwiek ze stron, spory będą rozstrzygane przez właściwy sąd powszechny, zgodnie z pkt 4 niniejszego rozdziału<br />4. Sądowe rozstrzyganie sporów:<br />a) Ewentualne spory powstałe pomiędzy Usługodawcą, a Usługobiorcą będącym jednocześnie Konsumentem zostają poddane sądom właściwym zgodnie z przepisami kodeksu postępowania cywilnego z dnia 17 listopada 1964 r. (Dz. U. Nr 43, poz. 296 ze zm.).<br />b) Ewentualne spory powstałe pomiędzy Usługodawcą, a Usługobiorcą niebędącym jednocześnie Konsumentem zostają poddane sądowi właściwemu ze względu na miejsce zamieszkania Usługodawcy.<br />5. Usługobiorca będący Konsumentem ma również prawo do skorzystania z pozasądowych sposobów rozstrzygania sporów w szczególności poprzez złożenie po zakończeniu postępowania reklamacyjnego wniosku o wszczęcie mediacji lub wniosku o rozpatrzenie sprawy przez sąd polubowny (wniosek można pobrać na stronie internetowej http://www.uokik.gov.pl/download.php?plik=6223). Wykaz Stałych Polubownych Sądów Konsumenckich działających przy Wojewódzkich Inspektoratach Inspekcji Handlowej dostępny jest na stronie internetowej: http://www.uokik.gov.pl/wazne_adresy.php#faq596). Konsument może skorzystać także z bezpłatnej pomocy powiatowego (miejskiego) rzecznika konsumentów lub organizacji społecznej, do której zadań statutowych należy ochrona konsumentów. Pozasądowe dochodzenie roszczeń po zakończeniu postępowania reklamacyjnego jest bezpłatne.<br />6. Konsument w celu polubownego rozwiązania sporu może w szczególności złożyć skargę za pośrednictwem platformy internetowej ODR (Online Dispute Resolution), dostępnej pod adresem: http://ec.europa.eu/consumers/odr/.</p>
          </p>
        </div>
      </div>
    </div>
  );
};
